substitutions:
  i2c_sda_pin: GPIO35
  i2c_scl_pin: GPIO36

external_components:
  - source: github://pr#4105
    components:
      [display_menu_base, graphical_display_menu, display, graph, font]

i2c:
  scl: ${i2c_scl_pin}
  sda: ${i2c_sda_pin}
  frequency: 400khz

display:
  - platform: ssd1306_i2c
    id: oled
    model: "SH1106 128x64"
    pages:
      - id: page_main
        lambda: |-
          if(id(rain_sensor).state){
            it.print(0, 20, id(mdi_24), "\U000F0596");
          }
          it.line(30, 0, 30, 64);
          it.print(43, 10, id(mdi_24), "\U000F050F");
          it.printf(36, 34, id(roboto), "%.1f°C", id(local_temperature).state);
          it.line(83, 0, 83, 64);
          if(id(fan_mode).active_index() == 0){
            it.print(96, 10, id(mdi_24), "\U000F0210");
            if(id(my_fan).state)
              it.printf(96, 34, id(roboto), "%d%%", id(my_fan).speed);
            else
              it.print(96, 34, id(roboto), "Off");
          }
          else{
            it.print(96, 10, id(mdi_24), "\U000F171D");
            it.printf(86, 34, id(roboto), "%.0f°C", id(fan_climate).target_temperature);
          }
    invert: false
    contrast: 30%

graphical_display_menu:
  id: oled_menu
  font: roboto
  display: oled
  active: true
  mode: rotary
  on_redraw:
    then:
      component.update: oled
  items:
    - type: command
      text: "Exit"
      on_value:
        - display_menu.hide: oled_menu
    - type: switch
      immediate_edit: false
      text: "Rain Sensor"
      on_text: "\U00002713"
      off_text: "X"
      switch: rain_sensor_enable
    - type: select
      text: Mode
      select: fan_mode
    - type: select
      text: Direction
      select: fan_direction

script:
  id: display_wakeup
  mode: restart
  then:
    - lambda: id(oled).turn_on();
    - delay: 1 min
    - lambda: id(oled).turn_off();
    - display_menu.hide: oled_menu

font:
  - file: "gfonts://Anonymous Pro"
    id: roboto
    size: 14
    glyphs:
      [
        " ",
        "!",
        '"',
        "%",
        (,
        ),
        +,
        ",",
        "-",
        .,
        /,
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        ":",
        "=",
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        a,
        b,
        c,
        d,
        e,
        f,
        g,
        h,
        i,
        j,
        k,
        l,
        m,
        n,
        o,
        p,
        q,
        r,
        s,
        t,
        u,
        v,
        w,
        x,
        y,
        z,
        °,
        "<",
        ">",
        "[",
        "]",
        "^",
        "*",
        "\U00002715",
        "\U00002713",
      ]
  - file: "gfonts://Material Icons" 
    id: mdi_24
    size: 24
    glyphs: [
        "\U000F0596", #weather-pouring
        "\U000F050F", #thermometer
        "\U000F0210", #fan
        "\U000F171D", #fan-auto
      ]
