substitutions:
  device_name: "opentasticfan"
  friendly_name: "OpentasticFan"
  #   temperature_sensor: remote_temperature
  endstop_current: "120" #Sets the current threshold in mA that turns the endstops on. May need to be adjusted for different cover motors
  rain_threshold: "300" #Sets the touch threshold for rain detection. This may need to be tweeked depending on your wiring.

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

  project:
    name: silverchris.opentasticfan-v3
    version: "1.0"

  on_boot:
    - priority: -100
      then:
        - cover.close: vent_lid
        - select.set:
            id: close_reason
            option: "BOOT"

esp32:
  board: dfrobot_firebeetle2_esp32s3
  variant: esp32s3
wifi:
  ap:
    password: opentasticfan

# Enable logging
logger:
  level: DEBUG

api:

ota:

packages:
  display:
    url: https://github.com/silverchris/opentasticfan
    file: config/3.0/display.yaml

  local_temperature:
    url: https://github.com/silverchris/opentasticfan
    file: config/3.0/temperature_analog.yaml

  climate:
    url: https://github.com/silverchris/opentasticfan
    file: config/3.0/climate.yaml

  cover:
    url: https://github.com/silverchris/opentasticfan
    file: config/3.0/cover.yaml

  rain:
    url: https://github.com/silverchris/opentasticfan
    file: config/3.0/rain.yaml

  control:
    url: https://github.com/silverchris/opentasticfan
    file: config/3.0/control.yaml

dashboard_import:
  package_import_url: github://silverchris/opentasticfan/config/3.0/example.yaml@main
  import_full_config: false

esp32_improv:
  authorizer: none

improv_serial:

captive_portal: