esphome:
  name: rvfan
  on_boot:
    - priority: -100
      then:
        - cover.close: vent_lid
        - select.set:
            id: close_reason
            option: "BOOT"

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    # platform_version: 3.4.0
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
wifi:
  ssid:
  password:

# Enable logging
logger:
  level: DEBUG

api:

ota:
  password: ""

substitutions:
  #   temperature_sensor: remote_temperature
  endstop_current: "120" #Sets the current threshold in mA that turns the endstops on. May need to be adjusted for different cover motors
  rain_threshold: "300" #Sets the touch threshold for rain detection. This may need to be tweeked depending on your wiring.

packages:
  display:
    url: https://github.com/silverchris/opentasticfan
    file: config/2.0/display.yaml

  dallas:
    url: https://github.com/silverchris/opentasticfan
    file: config/2.0/temperature_dallas.yaml

  climate:
    url: https://github.com/silverchris/opentasticfan
    file: config/2.0/climate.yaml

  cover:
    url: https://github.com/silverchris/opentasticfan
    file: config/2.0/cover.yaml

  rain:
    url: https://github.com/silverchris/opentasticfan
    file: config/2.0/rain.yaml

  control:
    url: https://github.com/silverchris/opentasticfan
    file: config/2.0/control.yaml

