dallas:
  pin: ${temperature_pin}
  update_interval: 5s

sensor:
  - platform: dallas
    index: 0
    id: local_temperature
    name: "Air Temperature"
    filters:
      - sliding_window_moving_average:
          window_size: 5
